### ISSUE TITLE
"Unspecified" service displayed in the Instana application dependency graph 

### ISSUE THREAD

**Issue by m-dilorenzi** [instana/opentelemetry-demo#4]
# Bug Report

After setting up the OTel Demo using the Kubernetes with Helm Chart, an "Unspecified" service is shown in the Instana dependency map.

![image](https://user-images.githubusercontent.com/52289654/234931215-be30ba3a-7c2f-47aa-8edd-736a5eeeaa47.png)

The service receives requests from the load generator and then sends requests to the frontend service and others, like the frontend service behavior except for some services reached. It's labelled with "HTTP" and "OPENTELEMETRY".

Do you have any suggestion about which service is it and what does it do?

**Comment by styblope** [comment]
Some of the Unspecified calls might refer to the calls to the Instana agent. These can be filtered out as "synthetic" calls in the Services configuration. We should add some instructions how to create the synthetic calls filters.

But there is also an issue with service name matching in Kubernetes and Helm. As you see in the picture there are two representations of the frontend service: "frontend" and "my-otel-demo-frontend" which should in fact be just one instance. The mismatch is because Helm diverts from the internal service naming and uses the instance prefix ("my-otel-demo") which then happens to be the DNS-resolved service name used by Instana for downstream service correlation. This can also result in some calls ending up as Unspecified. The dilemma is whether we should modify the Helm chart, thus forking and maintaining a separate Helm repo, or rather devise some post-install steps that will override the upstream Helm service names. Ideas are welcome! The docker-based installation does not suffer from this problem.

**Comment by styblope** [comment]
I've suppressed the Unspecified calls by marking the internal calls (rpresented by endpoint "HEAD /com.instana.plugin.python.2575049") as Synthetic in Instana: Services -> Configure Services -> Synthetic Endpoints -> "endpoint.name containts com.instana". Adding this tip to the troubleshooting document.
